# Atom One Light
set -g status-style fg=#383a42,bg=#fafafa
set -g status-right '#[fg=#a0a1a7]mode:#{client_key_table} #[fg=#d0d3db]| #[default]%Y-%m-%d %H:%M '
setw -g window-status-current-format '#[fg=#ffffff,bg=#4078f2,bold] #I:#W #[default]'
setw -g window-status-activity-style fg=#c18401,bold
set -g message-style fg=#ffffff,bg=#0997b3,bold
set -g mode-style fg=#ffffff,bg=#50a14f,bold
setw -g pane-border-format ' #{?pane_active,#[fg=#4078f2,bold],#[fg=#a0a1a7]}#T #[default]'
setw -g pane-border-style fg=#d7dae0
setw -g pane-active-border-style fg=#4078f2
