# Catppuccin Mocha
set -g status-style fg=#cdd6f4,bg=#1e1e2e
set -g status-right '#[fg=#6c7086]mode:#{client_key_table} #[fg=#585b70]| #[default]%Y-%m-%d %H:%M '
setw -g window-status-current-format '#[fg=#1e1e2e,bg=#89b4fa,bold] #I:#W #[default]'
setw -g window-status-activity-style fg=#f9e2af,bold
set -g message-style fg=#1e1e2e,bg=#94e2d5,bold
set -g mode-style fg=#1e1e2e,bg=#a6e3a1,bold
setw -g pane-border-format ' #{?pane_active,#[fg=#89b4fa,bold],#[fg=#6c7086]}#T #[default]'
setw -g pane-border-style fg=#45475a
setw -g pane-active-border-style fg=#89b4fa
