# Catppuccin Latte
set -g status-style fg=#4c4f69,bg=#eff1f5
set -g status-right '#[fg=#9ca0b0]mode:#{client_key_table} #[fg=#bcc0cc]| #[default]%Y-%m-%d %H:%M '
setw -g window-status-current-format '#[fg=#eff1f5,bg=#1e66f5,bold] #I:#W #[default]'
setw -g window-status-activity-style fg=#df8e1d,bold
set -g message-style fg=#eff1f5,bg=#179299,bold
set -g mode-style fg=#eff1f5,bg=#40a02b,bold
setw -g pane-border-format ' #{?pane_active,#[fg=#1e66f5,bold],#[fg=#9ca0b0]}#T #[default]'
setw -g pane-border-style fg=#ccd0da
setw -g pane-active-border-style fg=#1e66f5
