# Dracula
set -g status-style fg=#f8f8f2,bg=#282a36
set -g status-right '#[fg=#6272a4]mode:#{client_key_table} #[fg=#44475a]| #[default]%Y-%m-%d %H:%M '
setw -g window-status-current-format '#[fg=#282a36,bg=#bd93f9,bold] #I:#W #[default]'
setw -g window-status-activity-style fg=#f1fa8c,bold
set -g message-style fg=#282a36,bg=#8be9fd,bold
set -g mode-style fg=#282a36,bg=#50fa7b,bold
setw -g pane-border-format ' #{?pane_active,#[fg=#bd93f9,bold],#[fg=#6272a4]}#T #[default]'
setw -g pane-border-style fg=#44475a
setw -g pane-active-border-style fg=#bd93f9
