# Nord
set -g status-style fg=#d8dee9,bg=#2e3440
set -g status-right '#[fg=#4c566a]mode:#{client_key_table} #[fg=#434c5e]| #[default]%Y-%m-%d %H:%M '
setw -g window-status-current-format '#[fg=#2e3440,bg=#88c0d0,bold] #I:#W #[default]'
setw -g window-status-activity-style fg=#ebcb8b,bold
set -g message-style fg=#2e3440,bg=#5e81ac,bold
set -g mode-style fg=#2e3440,bg=#a3be8c,bold
setw -g pane-border-format ' #{?pane_active,#[fg=#88c0d0,bold],#[fg=#4c566a]}#T #[default]'
setw -g pane-border-style fg=#434c5e
setw -g pane-active-border-style fg=#88c0d0
