# One Half Dark
set -g status-style fg=#dcdfe4,bg=#282c34
set -g status-right '#[fg=#6f737b]mode:#{client_key_table} #[fg=#4b5263]| #[default]%Y-%m-%d %H:%M '
setw -g window-status-current-format '#[fg=#282c34,bg=#61afef,bold] #I:#W #[default]'
setw -g window-status-activity-style fg=#e5c07b,bold
set -g message-style fg=#282c34,bg=#56b6c2,bold
set -g mode-style fg=#282c34,bg=#98c379,bold
setw -g pane-border-format ' #{?pane_active,#[fg=#61afef,bold],#[fg=#5c6370]}#T #[default]'
setw -g pane-border-style fg=#4b5263
setw -g pane-active-border-style fg=#61afef
