# Solarized Dark
set -g status-style fg=#93a1a1,bg=#002b36
set -g status-right '#[fg=#586e75]mode:#{client_key_table} #[fg=#073642]| #[default]%Y-%m-%d %H:%M '
setw -g window-status-current-format '#[fg=#002b36,bg=#268bd2,bold] #I:#W #[default]'
setw -g window-status-activity-style fg=#b58900,bold
set -g message-style fg=#002b36,bg=#2aa198,bold
set -g mode-style fg=#002b36,bg=#859900,bold
setw -g pane-border-format ' #{?pane_active,#[fg=#268bd2,bold],#[fg=#586e75]}#T #[default]'
setw -g pane-border-style fg=#073642
setw -g pane-active-border-style fg=#268bd2
